services:
  app:
    platform: linux/amd64 # for M1 chip
    build:
      context: .
      dockerfile: ./Dockerfile
    image: demo_svelte
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000 # dev
      - 3001:3001 # preview
    networks:
      - demo_svelte

networks:
  demo_svelte: